name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    container: veriblock/alt-integration-cpp-dev
    strategy:
      fail-fast: false
      matrix:
        flags: [
          "-DCLANG_TIDY=ON",
          "-DASAN=ON",
          "-DUBSAN=ON",
          "-DCMAKE_BUILD_TYPE=Release",
        ]
    env:
      CC: clang
      CXX: clang++
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v1
        name: checkout

      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg integrate install
      - name: cmake
        run: cmake . -Bbuild ${{ matrix.flags }} -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: build
        run: cmake --build build -- -j2
      - name: test
        run: cd build && ctest

  linux-gcc:
    runs-on: ubuntu-18.04
    env:
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v1
        name: checkout

      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg integrate install
      - name: cmake
        run: cmake . -Bbuild -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: build
        run: cmake --build build -- -j2

  windows:
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v1
        name: checkout

      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg integrate install
      - name: cmake
        run: cmake . -Bbuild -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: build
        run: cmake --build build --parallel 2
      - name: test
        run: cd build && ctes

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      CC: clang
      CXX: clang++
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v1
        name: checkout

      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg integrate install
      - name: cmake
        run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: build
        run: cmake --build build -- -j2
      - name: test
        run: cd build && ctest